# Site settings
author: Chris Kay
title: Chris Kay's Flatiron Experience
header-img: img/home-bg.png
email: chriskay25@gmail.com
copyright_name: Chris Kay
description: > # this means to ignore newlines until "baseurl:"
  I'll fill in a little later...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  chriskay25

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
